
title: LAB of Structural Biology
url: 'http://favorite106.github.io'
baseurl: '/favorite106.github.io' #change it according to your repository name



# Profile information
yourname: HyunKyu, Song  ## put your name
title: 'LAB of Structural Biology'  ## your title
location: Anam-Dong, Seongbuk-Gu, Seoul 136-701, Korea


## Social Profiles
#facebook: http://www.facebook.com  ## your facebook account url
#twitter: http://www.twitter.com  ## your twitter account url
#linkedin: http://www.linkedin.com  ## your linkedin account url
#dribbble: http://www.dribble.com  ## you dribbble account url
#foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
